name: Daily Chart

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 22 * * 0"
  
  workflow_dispatch:

jobs:
  chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install Dependncies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
          playwright install --with-deps chromium

      - name: Run Scraper
        env:
          DUQUESNE_LIGHT_USERNAME: ${{ secrets.DUQUESNE_LIGHT_USERNAME }}
          DUQUESNE_LIGHT_PASSWORD: ${{ secrets.DUQUESNE_LIGHT_PASSWORD }}
          GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          LAST_N_DAYS: ${{ secrets.LAST_N_DAYS }}
          EMAIL_SUBJECT: ${{ secrets.EMAIL_SUBJECT }}
        run: |
          python src/duquesne_bill.py


        
